version: '3.5'

services:

  gateway:
    image: gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
    - 8080:8080
    networks:
    - gateway-network

  customer1:
    image: customer:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
    - 8081:8080
    networks:
    - gateway-network

  customer2:
    image: customer:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
    - 8082:8080
    networks:
    - gateway-network

  customer3:
    image: customer:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
    - 8083:8080
    networks:
    - gateway-network

networks:
  gateway-network:
    external:
      name: gateway-network