controller:
  image: "jenkins/jenkins"
  tag: "2.263.1"

  # List of plugins to install in addition to those listed in master.installPlugins
  additionalPlugins: []

  initContainerEnv:
    - name: JENKINS_UC_DOWNLOAD
      value: http://ftp-nyc.osuosl.org/pub/jenkins
      
  JCasC:
    enabled: false
    defaultConfig: false
    
  sidecars:
    configAutoReload:
      enabled: false

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1beta1"
    hostName: jenkins.cicd.com
    annotations: 
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/rewrite-target: /
      traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"


